language: node_js
node_js:
- 6.0.0
- 6.9.4
- 7.0.0
- 7.4.0
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_DEFAULT_OUTPUT=json
  - secure: MphuBNlR5Mlznb7cLVUMJAt1lvPmHTT0oDtCZpStG1F3EIDoncwJ16FtMZKXrVImb/e28KOELhEcFqpG+WvusjmI+uyAJKrDuMkOk/XHNlC1oI3h4vvWougj9ge7GA+koidQIdMeFZtX6ZyZW5NtGDEWx2Vru9pdONWyTBk10mRNSuMVU5d1jv7wgjig2deYtclZXF9PvVycgUiL5yTfMeV2c9hjpArgfTruybpJ9msSXNKdXmm4Qg52Ta1xdI5mKMNf0elQB3J57Nn9PMzCtN7gtRQtDB757WXQydlGne5rWDkY5XhCr3ZEG4xcORif17eRRZ8jMVaCiVLWI9xLoxb5EMYzgZ8Takn0oh+vFmkPyAgOq57q22UA4uBUJF1xu3/LN7lpbSy2wwuxsKbBIIKt+r6uCeSufBbAKfgxi9k3z7+INKZcohsx51aLqzlP+RjraB2NFirUruhuqoTXW9DxcnAI4qKL09U9QyNCgc+ood3Ambro0zd15yyPer9n6f/5dymNv0bWfU/EJBegAi24AXTBUkmHl9vBDnU5NH8kcUaRBGOLHr6tOHInDVLOrpwl/aiQtFTlIfnvB9JrqnT0jBr7XdFrBvDtsFGnR0vmakQ93eeex2LrJnE1RxB5lH2g50aCusBrfS2zh1vXshomLc+pLMXeb2CIhvJP9pM=
  - secure: CZvurtQhH/pbGX+m3Ou/EAWVKBVOcYk7xjlQ9H0oOleVYKRwafUrGiLuU5vCAhjYloyz7sbj9SSDq/VDVJdemtaEKPgyvRIz11Y8qUfhUOPGsEdop1Mt2BR9jUUjn7H0nn0PhfLdRMbERM07cnps+3roG5pItVG5fi541ZUodVUU7L2xDFMkqzvOFy5gZCDIomeaz3pEGCX8ZKZ66kb5laTGltManJqbiPNeQ+4Niyz2+m7dwFdA+nh4E2JyhVGW6gUPshyH7x1080OZeHp209/vKaWtfLH6kMazFQF/1lMzlvOVhzfaXrGvs/4lF8F2Ts5RJYlT8VYdOCVpijPwTh+bFhE+oAi5IntD3GoVzlQI6kVSdTl00m+GsTeTi6YhI96DR3iFoOpAwUybVWuIfkr49eP1hX2cQ4jzb3U0RsKOIZhN3r9GSuz9O7bueDojcJ+qt9HvwB6jng9UsI/lyIgY2y9bjfchC4ttx2Xk+yyFV2ATD9O2IbGYuKkEaJIGM3IwLL5vt6iTOmY5QZLuR3ZPIxOyOdliU3JmGw+sQMsa8qUp8802hk+7YGu9r+jGJGUL+vTvA1SJYXCNE1zo+gPC0G/7wl0n7r3ot4mCCxsoLtBX4HYX6GMud1ontSAaffPznZkpEx0C6H5ao6BEqyTFvmeJv63tskSsnG+pD1A=
deploy:
  provider: npm
  email: admin@cmr1.com
  api_key:
    secure: QahMPoX+N5e7blguwQCFsinZqpZQydPKIXGNDAaqYD+10W3hzm4CNGl1/FC2J3yorWk8CSKHpcPbQ74Hm100dtEE2ceukkJa7fiTg2YdTu/W8WfmpB5UYDhln7aL6hpT3dB3uzmA7QfjoniUGfOO9MvW1Z7gWmtm6BY6CcYfewoZW7C93yll+jQbFaA1NiSaTCwdaycgH2pd0I3T7pN+7b2J+wZvB7PhOrKUS5SYivHSvsom29rKZF8iBoXf7uwIohtkAUX0DsR1hy8wBXi5JsE7NelAABAdH8gHB6auXpRP0akoK94D8ehwGpHaTzJYg8KDuo6F9L5mWq928XdozgRBdYFhW1DDkBSqstSAueXdc+GJnRFR9wr2w14uE+BIJFZ+IUICrqnnbgHw2As6uXm3TgPtBJJN96h27fxZkn4rbTS5Qil7bYK/JfYjYAdAIbxLGIHms3avgCxaE4DBchOo8vNAw7Wv2cs5SKvk5O2yQ3MPMKcPs5RlLdX1gSQ6K0jdhm4xwciY2x/SY/Tr4zQ5Sk3GvUq8V585/Z7rnTj7myU2xE6xjPknfc6d8k92BDikAo97VGMeEt0qPPhN9tv6wzFGreGvy+9Zvr1n88yjlMuG1hg0S04T4UYgUR91UbXVS4qqugD7lmTfqDfaOrSu3fBmXQKgh0rDquUOmCE=
  on:
    tags: true
    repo: cmr1/aws-node
