language: node_js
node_js:
- 6.0.0
- 6.7.0
- 6.9.4
- 7.0.0
- 7.4.0
branches:
  only:
    - /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z\-]+(?:\.[\da-z\-]+)*)?(?:\+[\da-z\-]+(?:\.[\da-z\-]+)*)?\b/ig
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_DEFAULT_OUTPUT=json
  - secure: J4nbumt7NDRaNH/FeZ5vZ0DNbPOenfgF1ZoUjtmXuBgACmUFcVJ9oyAqq0ZNd5hsjulG/BzHPQiRDVdpjxZFi5hUAFhdiLD445F56XV2wP2QNBTolufq+yrIxYj0AtkUQVi5WineeOGwR+3LDmn9Ga9HXpJg04Pn8X3qE7BbvCllbLg7360FZKP85UMa7/kgElCZed3Z1w9/hbwLZMCtfE9PsqbwU1HLLSsmivJbIS8RD9lW2gbiWY0xenChmlpHk9ux3/QvzpENVIAoFKPS0H/xdiFC+P61ysM6wChFjMBT/OXTaWs0mSn82jG74/k/FYtkp0oKeUyQAu0mhEbtxiULPtrkKdGRvXHjVFBNcaveg5RMX/HZ75whepAUyIVKV531SxKwXWXtZCahk/JGChDcnhefcgLIS+x7QKRXmOO9LtBui0YdatADxoBIGHVuZINmPASqESqdPogtgZlaqcSwyHrqPx9g31ZzF2SN8CptPeaMEkdBFVThG1CVqLywsnOlxpCjXc8T8SrtDPsHqT7TdKTjc6uBzdaMC080k41wnsIiHYy+Yb5wO6JyAeezcQ9rtc0xBmXSIpTtmn7n6JCdREvJPJK50ZJ0uLq6KNYz3lsoKYflgpx52IdTqLhZzDsK9++dC2Y2myVncUcdMwjPqKL7rtR56TBUsVTVcOQ=
  - secure: HrNr5F+8cZiyS/Q/PVAJ74r4+jFMZdgOzFxUHrKo+2Q4CD+1gZi+Mz19wcvcmz74NG/HF9J/ORyoy7NwDP9pMyEt6ZJNXWW7dfVm4q1cT6GaSnDm8kP98fAnlU2NWXHrv9lvDIazpDrEep2olOefxKd+1d1iUlJnwPZwAantDglsVyQuC6kp/1o+C8ld5SYrxPXElE3pj7xaW7ccEAjCt42XUxyttv151IMWVS3XqfNjWrepkAVuXV6eFqsK+WP+P6ccGFtuZsTr3rsngjiq16eo4Ppc6P98Wp0GpXRxVLEkWhBNU72jYGxTQCkK6lOIiQ1GkeLXiiC1C4X1uy7kP8GWdgEler7eEC+MCkk0Dv28Lyjq+RI1f9y0zfw3xSDRfjgj/n/F2ojqJJ3c2OZ6QGkiec2BXvw+5HvWhd+WkHqmYkxZzPJKwYkQtlcB8JnTNUpBPlVcZvjpa2W2Dm6ChwXlLfXecYUA6oBE71qJdzQ+j8e3xIfCUowJbvKchGQG8Ut3+w9egy+9M5vFtJr72Mni1c9Wd5Ck2Rx6Aj289xPIMJmo+nuK3pT1JF9+L1Ga9+HWzy20i31is7f3znT2Wv198wCWbJyCrwjJyrETmsDhHamSMx57gIeFYKGU/yZOLN3yM/DxIevUirAfYGquKidQ5uIFuwd0LebDHcLh1hw=
deploy:
  provider: npm
  email: admin@cmr1.com
  api_key:
    secure: QahMPoX+N5e7blguwQCFsinZqpZQydPKIXGNDAaqYD+10W3hzm4CNGl1/FC2J3yorWk8CSKHpcPbQ74Hm100dtEE2ceukkJa7fiTg2YdTu/W8WfmpB5UYDhln7aL6hpT3dB3uzmA7QfjoniUGfOO9MvW1Z7gWmtm6BY6CcYfewoZW7C93yll+jQbFaA1NiSaTCwdaycgH2pd0I3T7pN+7b2J+wZvB7PhOrKUS5SYivHSvsom29rKZF8iBoXf7uwIohtkAUX0DsR1hy8wBXi5JsE7NelAABAdH8gHB6auXpRP0akoK94D8ehwGpHaTzJYg8KDuo6F9L5mWq928XdozgRBdYFhW1DDkBSqstSAueXdc+GJnRFR9wr2w14uE+BIJFZ+IUICrqnnbgHw2As6uXm3TgPtBJJN96h27fxZkn4rbTS5Qil7bYK/JfYjYAdAIbxLGIHms3avgCxaE4DBchOo8vNAw7Wv2cs5SKvk5O2yQ3MPMKcPs5RlLdX1gSQ6K0jdhm4xwciY2x/SY/Tr4zQ5Sk3GvUq8V585/Z7rnTj7myU2xE6xjPknfc6d8k92BDikAo97VGMeEt0qPPhN9tv6wzFGreGvy+9Zvr1n88yjlMuG1hg0S04T4UYgUR91UbXVS4qqugD7lmTfqDfaOrSu3fBmXQKgh0rDquUOmCE=
  on:
    tags: true
    repo: cmr1/node-aws
